[package]
name = "serde_snyk_container"
version = "0.1.0"
edition = "2021"
description = "Serde-compatible data models for the Snyk Container report format"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fulgas/snyk-to-md-rs"
homepage = "https://github.com/fulgas/snyk-to-md-rs"
documentation = "https://docs.rs/serde-snyk-container"
keywords = ["snyk", "serde", "security", "vulnerability", "schema"]
categories = ["encoding", "parsing"]
authors = ["Nelson Silva <nelson.emanuel.silva@gmail.com>"]
readme = "README.md"
rust-version = "1.90"

[lib]
name = "serde_snyk_container"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.228", features = ["derive", "default"] }
serde_json = "1.0.145"

[build-dependencies]
prettyplease = "0.2.37"
serde = { version = "1.0.228"}
serde_json = "1.0.145"
syn = "2.0.109"
typify = { version = "0.5.0"}